language: node_js
node_js: '0.10'
install:
  - npm install
  - npm install -g istanbul codeclimate-test-reporter
script:
  - make cover
  - CODECLIMATE_REPO_TOKEN=9262502099caf6f03f3a286f97c4a2c6c3b6220559507986be7c6ed9e1a81b90 codeclimate < coverage/lcov.info
